#!/usr/local/bin/node

// Needed to require express locally; it does a require('connect')
require.paths.unshift(__dirname + '/deps/connect/lib');

require.paths.push(__dirname);
require.paths.push(__dirname + '/lib');
require.paths.push(__dirname + '/deps');

// Add node directory for things like qs (connect depends on it)
require.paths.push('/usr/local/lib/node');

require('controlServer').listen(process.argv[2] || 3000);
