#!/usr/local/bin/node

// nodeunit's default reporter depends on process.cwd
process.chdir(__dirname);

require.paths.unshift(__dirname + '/deps/nodeunit/lib');
require.paths.push(__dirname);
['lib', 'deps', 'test'].forEach(function (dir) {
    require.paths.push(__dirname + '/' + dir);
});

var tests = process.argv.slice(2);
if (tests.length === 0) {
    tests.push('test/unit');
    tests.push('test/functional');
}

var testrunner = require('nodeunit').reporters.default;
testrunner.run(tests);
