#!/usr/bin/env node
// vim: ft=javascript

var basedir = __dirname.replace(/[^\/]+$/, '');

// Needed to require express locally; it does a require('connect')
require.paths.unshift(basedir + '/deps/connect/lib');

require.paths.push(basedir);
require.paths.push(basedir + '/lib');
require.paths.push(basedir + '/deps');

// Add node directory for things like qs (connect depends on it)
require.paths.push('/usr/local/lib/node');

var server = require('controlServer').create(process.argv[2] || 3000);

require('fs').writeFileSync('httpmock.pid', process.pid.toString());

process.on('SIGTERM', function () {
    server.close();
});
