#!/usr/bin/env node
// vim: ft=javascript
'use strict';

var basedir = __dirname.replace(/\w+$/, '');

// Needed to require express locally; e.g. it does a require('connect')
['connect/lib', 'qs', 'mime'].forEach(function (path) {
    require.paths.unshift(basedir + '/deps/' + path);
});

require.paths.push(basedir);
require.paths.push(basedir + '/lib');
require.paths.push(basedir + '/deps');

var server = require('controlServer').create(process.argv[2] || 3000);

require('fs').writeFileSync('httpmock.pid', process.pid.toString());

process.on('SIGTERM', function () {
    server.close();
});
